// <auto-generated />
using System;
using DCartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DcartAPI.Migrations
{
    [DbContext(typeof(DCartAPIContext))]
    partial class DCartAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCartAPI.Models.Carts.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("DCartAPI.Models.Carts.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUppdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInCart")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DCartAPI.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DCartAPI.Models.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUppdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInCart")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DCartAPI.Models.Products.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6104),
                            Name = "Electronics",
                            PosterImageUrl = "Images/Categories/electronics.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6106),
                            Name = "Furnitures",
                            PosterImageUrl = "Images/Categories/furniture.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6108),
                            Name = "Toys",
                            PosterImageUrl = "Images/Categories/toys.jpg"
                        });
                });

            modelBuilder.Entity("DCartAPI.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("PosterImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6333),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/dellxps.png",
                            ProductName = "Dell XPS",
                            ProductPrice = 17567m,
                            QuantityInStock = 23,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6335),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/microsoft-surface.png",
                            ProductName = "Microsoft Surface",
                            ProductPrice = 23890m,
                            QuantityInStock = 12,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6338),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/panasonic-tv.png",
                            ProductName = "Panasonic 4k TV",
                            ProductPrice = 29349m,
                            QuantityInStock = 6,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6339),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/sony-lcd-tv.png",
                            ProductName = "Sony LCD TV",
                            ProductPrice = 18945m,
                            QuantityInStock = 13,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6341),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/ikea-chair.png",
                            ProductName = "Ikea Chair",
                            ProductPrice = 129m,
                            QuantityInStock = 239,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6343),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/ikea-soft-chair.png",
                            ProductName = "Ikea Soft Chair",
                            ProductPrice = 429m,
                            QuantityInStock = 64,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6345),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/ikea-table.png",
                            ProductName = "Ikea Table",
                            ProductPrice = 349m,
                            QuantityInStock = 123,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6347),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/ikea-glass-table.png",
                            ProductName = "Ikea Glass Table",
                            ProductPrice = 439m,
                            QuantityInStock = 123,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6348),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/action-figure.png",
                            ProductName = "Action Figure",
                            ProductPrice = 599m,
                            QuantityInStock = 38,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6350),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/toy-story-collection.png",
                            ProductName = "Ikea Table",
                            ProductPrice = 349m,
                            QuantityInStock = 12,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6352),
                            IsFeatured = false,
                            PosterImageUrl = "Images/Products/doll.png",
                            ProductName = "Dolly The Doll",
                            ProductPrice = 659m,
                            QuantityInStock = 457,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6353),
                            IsFeatured = true,
                            PosterImageUrl = "Images/Products/toy-story-doll.png",
                            ProductName = "Toy Story Doll",
                            ProductPrice = 189m,
                            QuantityInStock = 21,
                            SubCategoryId = 6
                        });
                });

            modelBuilder.Entity("DCartAPI.Models.Products.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6219),
                            MainCategoryId = 1,
                            Name = "Computers",
                            PosterImageUrl = "/Images/SubCategories/computers.png"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6221),
                            MainCategoryId = 1,
                            Name = "Tvs",
                            PosterImageUrl = "/Images/SubCategories/tv.png"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6223),
                            MainCategoryId = 2,
                            Name = "Chairs",
                            PosterImageUrl = "/Images/SubCategories/chair.png"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6225),
                            MainCategoryId = 2,
                            Name = "Tables",
                            PosterImageUrl = "/Images/SubCategories/table.png"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6226),
                            MainCategoryId = 3,
                            Name = "Action Figures",
                            PosterImageUrl = "/Images/SubCategories/toys.png"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2022, 11, 16, 11, 4, 5, 241, DateTimeKind.Utc).AddTicks(6228),
                            MainCategoryId = 3,
                            Name = "Dolls",
                            PosterImageUrl = "/Images/SubCategories/dolls.png"
                        });
                });

            modelBuilder.Entity("DCartAPI.Models.Users.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DCartAPI.Models.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DCartAPI.Models.Carts.CartItem", b =>
                {
                    b.HasOne("DCartAPI.Models.Carts.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("DCartAPI.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("DCartAPI.Models.Orders.Order", "Cart")
                        .WithMany("OrderItem")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("DCartAPI.Models.Products.Product", b =>
                {
                    b.HasOne("DCartAPI.Models.Products.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("DCartAPI.Models.Products.SubCategory", b =>
                {
                    b.HasOne("DCartAPI.Models.Products.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("DCartAPI.Models.Users.Address", b =>
                {
                    b.HasOne("DCartAPI.Models.Users.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("DCartAPI.Models.Users.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DCartAPI.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DCartAPI.Models.Orders.Order", b =>
                {
                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("DCartAPI.Models.Products.MainCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DCartAPI.Models.Products.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DCartAPI.Models.Users.User", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
